#!/usr/bin/env python3
"""Generator: build src/emoji.zig from the gemoji shortcode database.

Source data: https://github.com/github/gemoji `db/emoji.json` (MIT licensed;
the emoji names are GitHub's shortcode set, the characters come from the
Unicode emoji data files gemoji is generated from). One record per emoji, each
carrying an `aliases` list -- those aliases ARE the `:shortcode:` names.

Usage (run from the repo root):

    python3 scripts/_gen-emoji.py                      # fetches the DB
    python3 scripts/_gen-emoji.py db/emoji.json        # or use a local copy
    python3 scripts/_gen-emoji.py db/emoji.json src/emoji.zig

Produces a Zig module shaped like src/entity.zig: a table sorted by name plus a
binary search over it. Unlike the entity table the names carry no delimiters --
the parser strips the surrounding colons before probing -- and the payload is
the emoji's UTF-8 bytes rather than codepoints, because a fair number of
shortcodes (`heart`, `warning`, every flag, every skin-tone variant) expand to
a multi-codepoint sequence with variation selectors / ZWJ that the parser has
no business re-encoding.

Never hand-edit src/emoji.zig; re-run this instead.
"""

import json
import sys
import urllib.request

SRC_URL = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"

SRC = sys.argv[1] if len(sys.argv) > 1 else SRC_URL
OUT = sys.argv[2] if len(sys.argv) > 2 else "src/emoji.zig"

if SRC.startswith("http://") or SRC.startswith("https://"):
    with urllib.request.urlopen(SRC) as resp:
        db = json.loads(resp.read().decode("utf-8"))
else:
    with open(SRC, "r", encoding="utf-8") as f:
        db = json.load(f)

# alias -> emoji. First record wins; gemoji has no duplicate aliases today, so
# a collision means the upstream data changed shape and is worth failing on.
entries = {}
for record in db:
    char = record["emoji"]
    for alias in record["aliases"]:
        if alias in entries and entries[alias] != char:
            raise SystemExit(f"Conflicting alias {alias!r}")
        entries[alias] = char

if not entries:
    raise SystemExit("No entries parsed!")

# The parser's shortcode recognizer accepts exactly this byte class, so a name
# outside it would be unreachable -- fail instead of shipping dead rows.
NAME_CHARS = set("abcdefghijklmnopqrstuvwxyz0123456789_+-")
for name in entries:
    bad = set(name) - NAME_CHARS
    if bad:
        raise SystemExit(f"Alias {name!r} uses bytes outside the recognizer's class: {sorted(bad)}")

# Byte order, which is what the Zig binary search compares with.
names = sorted(entries, key=lambda s: s.encode("utf-8"))
max_name_len = max(len(n.encode("utf-8")) for n in names)

# Selectivity of the (first byte, length) reject filter emitted below, quoted in
# the generated file's comment so it cannot drift from the data.
first_bytes = {n[0] for n in names}
occupied_pairs = len({(n[0], len(n.encode("utf-8"))) for n in names})
possible_pairs = len(first_bytes) * max_name_len


def zig_escape(s):
    """Emit the emoji as \\u{...} escapes so src/emoji.zig stays pure ASCII."""
    return "".join(f"\\u{{{ord(ch):X}}}" for ch in s)


lines = []
lines.append("// AUTO-GENERATED by scripts/_gen-emoji.py from github/gemoji's db/emoji.json")
lines.append("// (MIT) — do not edit by hand.")
lines.append("//")
lines.append("// Emoji shortcode table: the `:name:` names GitHub publishes, mapped to the")
lines.append("// emoji's UTF-8 bytes. Probed by the inline mark collector; see")
lines.append("// src/parser/inlines.zig.")
lines.append("")
lines.append("const std = @import(\"std\");")
lines.append("")
lines.append("/// Shortcode record: the bare name (no colons) and the emoji's UTF-8 bytes.")
lines.append("pub const EMOJI = struct {")
lines.append("    name: []const u8,")
lines.append("    chars: []const u8,")
lines.append("};")
lines.append("")
lines.append("/// Longest name in the table. The collector uses it to bound its name scan,")
lines.append("/// so a stray `:` in ordinary text costs a handful of byte tests at most.")
lines.append(f"pub const MAX_NAME_LEN = {max_name_len};")
lines.append("")
lines.append("/// Sorted by name in byte order — `emoji_lookup`'s binary search depends on it.")
lines.append(f"const EMOJI_MAP = [{len(names)}]EMOJI{{")
for name in names:
    lines.append(f'    .{{ .name = "{name}", .chars = "{zig_escape(entries[name])}" }},')
lines.append("};")
lines.append("")
lines.append("/// Reject filter, derived from the table above at comptime rather than emitted:")
lines.append("/// bit `len` of `NAME_LEN_MASK[first byte]` is set iff the table holds a name of")
lines.append(f"/// that length starting with that byte. Only {occupied_pairs} of the {possible_pairs} (first byte,")
lines.append("/// length) pairs the table's names could occupy actually are, so one load and")
lines.append("/// one bit test turns most `:looks_like_a_name:` runs away before the binary")
lines.append("/// search starts walking the table.")
lines.append("const NAME_LEN_MASK = blk: {")
lines.append(f"    @setEvalBranchQuota({len(names) * 8});")
lines.append("    var mask = [_]u64{0} ** 256;")
lines.append("    for (EMOJI_MAP) |e| mask[e.name[0]] |= @as(u64, 1) << @intCast(e.name.len);")
lines.append("    break :blk mask;")
lines.append("};")
lines.append("")
lines.append("/// Look up an emoji shortcode name (without the surrounding colons);")
lines.append("/// returns the emoji's UTF-8 bytes, or null if the name is unknown.")
lines.append("pub fn emoji_lookup(name: []const u8) ?[]const u8 {")
lines.append("    if (name.len == 0 or name.len > MAX_NAME_LEN) return null;")
lines.append("    if ((NAME_LEN_MASK[name[0]] >> @intCast(name.len)) & 1 == 0) return null;")
lines.append("")
lines.append("    var lo: usize = 0;")
lines.append("    var hi: usize = EMOJI_MAP.len;")
lines.append("    while (lo < hi) {")
lines.append("        const mid = lo + (hi - lo) / 2;")
lines.append("        switch (std.mem.order(u8, name, EMOJI_MAP[mid].name)) {")
lines.append("            .eq => return EMOJI_MAP[mid].chars,")
lines.append("            .lt => hi = mid,")
lines.append("            .gt => lo = mid + 1,")
lines.append("        }")
lines.append("    }")
lines.append("    return null;")
lines.append("}")
lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Parsed {len(names)} shortcodes (max name {max_name_len} bytes) -> {OUT}")
